/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class components_Worker */

#ifndef _Included_components_Worker
#define _Included_components_Worker
#ifdef __cplusplus
extern "C" {
#endif
#undef components_Worker_MIN_PRIORITY
#define components_Worker_MIN_PRIORITY 1L
#undef components_Worker_NORM_PRIORITY
#define components_Worker_NORM_PRIORITY 5L
#undef components_Worker_MAX_PRIORITY
#define components_Worker_MAX_PRIORITY 10L
/*
 * Class:     components_Worker
 * Method:    cppSetAffinity
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_components_Worker_cppSetAffinity
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
