#!/bin/sh -

Time=2
Writers=1
Readers=32

Reader=1
while [ ${Reader} -le ${Readers} ] ; do
    java -Djava.library.path=jni Harness ${1} ${Time} ${Reader} ${Writers} ${2}
    Reader=`expr ${Reader} + 1`
done
